### ISSUE TITLE
Link in documentation seems to be broken

### ISSUE THREAD

**Issue by lmikelionis** [ongr-io/ongr-sandbox#63]
Link (:doc:`/handbook/requirements`.) in: https://github.com/ongr-io/ongr-sandbox/blob/master/src/ONGR/DemoBundle/Resources/doc/index.rst 
seems to be broken.

**Comment by tautrimas** [comment]
Depends on https://github.com/ongr-io/ongr-handbook/issues/9. Closing, because on the later date, we will fix all these links or simply ignore and leave Sphinx rendering only.

Currently, it seems ok in Sphinx: http://ongr.readthedocs.org/en/latest/components/ongr-sandbox/src/ONGR/DemoBundle/Resources/doc/index.html
